//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novacta.Analytics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novacta.Analytics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm failed to converge..
        /// </summary>
        internal static string STR_EXCEPT_ALG_NOT_CONVERGING {
            get {
                return ResourceManager.GetString("STR_EXCEPT_ALG_NOT_CONVERGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category already exists in the variable having the same code or label..
        /// </summary>
        internal static string STR_EXCEPT_CAT_ALREADY_EXISTS_IN_VARIABLE_LIST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_ALREADY_EXISTS_IN_VARIABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain null values..
        /// </summary>
        internal static string STR_EXCEPT_CAT_CATEGORIZER_IS_NULL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_CATEGORIZER_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain keys not included in collection parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_CAT_CATEGORIZER_REFERS_TO_IRRELEVANT_KEY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_CATEGORIZER_REFERS_TO_IRRELEVANT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paremeter is not a category code in the variable represented by parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_CAT_CODE_NOT_IN_VARIABLE_LIST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_CODE_NOT_IN_VARIABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of columns equal to the number of variables in this instance..
        /// </summary>
        internal static string STR_EXCEPT_CAT_COLUMNS_NOT_EQUAL_TO_DATASET_VARIABLES {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_COLUMNS_NOT_EQUAL_TO_DATASET_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of columns equal to the number of items in parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_CAT_COLUMNS_NOT_EQUAL_TO_VARIABLES_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_COLUMNS_NOT_EQUAL_TO_VARIABLES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream contains not enough data to define a valid categorical data set..
        /// </summary>
        internal static string STR_EXCEPT_CAT_DATASET_NOT_ENOUGH_DATA {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_DATASET_NOT_ENOUGH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream line {0} must contain data for column {1}..
        /// </summary>
        internal static string STR_EXCEPT_CAT_DATASET_NOT_ENOUGH_ROW_DATA {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_DATASET_NOT_ENOUGH_ROW_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must contain a number of indexes equal to the number of feature variables in this instance..
        /// </summary>
        internal static string STR_EXCEPT_CAT_INDEXES_MUST_HAVE_SAME_COUNT_OF_FEATURES {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_INDEXES_MUST_HAVE_SAME_COUNT_OF_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix entry is not a category code in the variable corresponding to the entry column..
        /// </summary>
        internal static string STR_EXCEPT_CAT_MATRIX_ENTRY_NOT_IN_VARIABLE_LIST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_MATRIX_ENTRY_NOT_IN_VARIABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported for read-only variables..
        /// </summary>
        internal static string STR_EXCEPT_CAT_VARIABLE_IS_READONLY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CAT_VARIABLE_IS_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter contains a feature variable whose number of categories is not as expected by this instance..
        /// </summary>
        internal static string STR_EXCEPT_CEE_INVALID_FEATURE_CATEGORIES_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_INVALID_FEATURE_CATEGORIES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has not the number of categories expected by this instance..
        /// </summary>
        internal static string STR_EXCEPT_CEE_INVALID_RESPONSE_CATEGORIES_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_INVALID_RESPONSE_CATEGORIES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has not the count expected by this instance..
        /// </summary>
        internal static string STR_EXCEPT_CEE_INVALID_STATE_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_INVALID_STATE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s count must agree with the number of feature variables expected by this instance..
        /// </summary>
        internal static string STR_EXCEPT_CEE_MUST_HAVE_SAME_FEATURES_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_MUST_HAVE_SAME_FEATURES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A premise must be a subset of the corresponding feature domain..
        /// </summary>
        internal static string STR_EXCEPT_CEE_PREMISE_IS_NOT_FEATURE_SUBSET {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_PREMISE_IS_NOT_FEATURE_SUBSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a category code of the response variable defined by this instance..
        /// </summary>
        internal static string STR_EXCEPT_CEE_UNRECOGNIZED_RESPONSE_CODE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_UNRECOGNIZED_RESPONSE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} variable must define at least a category..
        /// </summary>
        internal static string STR_EXCEPT_CEE_VARIABLE_IS_EMPTY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEE_VARIABLE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given the current context, the parameter&apos;s value is incompatible with that of parameter &apos;{0}&apos;. To achieve compatibility, &apos;rarity&apos; should be decreased..
        /// </summary>
        internal static string STR_EXCEPT_CEM_TOO_HIGH_RARITY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEM_TOO_HIGH_RARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given the current context, the parameter&apos;s value is incompatible with that of parameter &apos;{0}&apos;. To achieve compatibility, &apos;rarity&apos; should be increased..
        /// </summary>
        internal static string STR_EXCEPT_CEM_TOO_LOW_RARITY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEM_TOO_LOW_RARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has not the dimensions expected by the specified context..
        /// </summary>
        internal static string STR_EXCEPT_CEP_PARAMETER_IS_CONTEXT_INCOMPATIBLE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEP_PARAMETER_IS_CONTEXT_INCOMPATIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has a number of columns that is not equal to the state dimension defined by the specified context..
        /// </summary>
        internal static string STR_EXCEPT_CEP_SAMPLE_IS_CONTEXT_INCOMPATIBLE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_CEP_SAMPLE_IS_CONTEXT_INCOMPATIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator is currently before the first or after the last item in the collection..
        /// </summary>
        internal static string STR_EXCEPT_ENU_OUT_OF_BOUNDS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_ENU_OUT_OF_BOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of columns equal to the number of active variables..
        /// </summary>
        internal static string STR_EXCEPT_GDA_COLUMNS_NOT_EQUAL_TO_ACTIVE_VARIABLES {
            get {
                return ResourceManager.GetString("STR_EXCEPT_GDA_COLUMNS_NOT_EQUAL_TO_ACTIVE_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disjoint form of the parameter has at least a non positive marginal sum. The principal information cannot be acquired..
        /// </summary>
        internal static string STR_EXCEPT_GDA_MCA_NON_POSITIVE_MARGINAL_SUMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_GDA_MCA_NON_POSITIVE_MARGINAL_SUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has at least a non positive marginal sum. The principal information cannot be acquired..
        /// </summary>
        internal static string STR_EXCEPT_GDA_NON_POSITIVE_MARGINAL_SUMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_GDA_NON_POSITIVE_MARGINAL_SUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No principal variable has positive variance. The principal information cannot be acquired..
        /// </summary>
        internal static string STR_EXCEPT_GDA_NON_POSITIVE_PRINCIPAL_VARIANCES {
            get {
                return ResourceManager.GetString("STR_EXCEPT_GDA_NON_POSITIVE_PRINCIPAL_VARIANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of rows equal to the number of active points..
        /// </summary>
        internal static string STR_EXCEPT_GDA_ROWS_NOT_EQUAL_TO_ACTIVE_POINTS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_GDA_ROWS_NOT_EQUAL_TO_ACTIVE_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TValue type: {0}. Expected: {1}..
        /// </summary>
        internal static string STR_EXCEPT_IDV_INVALID_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_IDV_INVALID_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last index must be greater than or equal to first one..
        /// </summary>
        internal static string STR_EXCEPT_IND_LAST_LESS_THAN_FIRST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_IND_LAST_LESS_THAN_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the increment is negative, then the index bound must be less than or equal to the first index..
        /// </summary>
        internal static string STR_EXCEPT_IND_NEGATIVE_INCREMENT_FIRST_LESS_THAN_LAST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_IND_NEGATIVE_INCREMENT_FIRST_LESS_THAN_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A position exceeds the dimensions of this instance..
        /// </summary>
        internal static string STR_EXCEPT_IND_POSITION_EXCEEDS_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_IND_POSITION_EXCEEDS_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the increment is positive, then the index bound must be greater than or equal to the first index..
        /// </summary>
        internal static string STR_EXCEPT_IND_POSITIVE_INCREMENT_LAST_LESS_THAN_FIRST {
            get {
                return ResourceManager.GetString("STR_EXCEPT_IND_POSITIVE_INCREMENT_LAST_LESS_THAN_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part contains an element which is not valid as a row index of the data..
        /// </summary>
        internal static string STR_EXCEPT_INP_PART_CONTAINS_INVALID_INDEX {
            get {
                return ResourceManager.GetString("STR_EXCEPT_INP_PART_CONTAINS_INVALID_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition operations, the dimensions of the right operand must match those of the left one..
        /// </summary>
        internal static string STR_EXCEPT_MAT_ADD_ALL_DIMS_MUST_MATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_ADD_ALL_DIMS_MUST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain null values..
        /// </summary>
        internal static string STR_EXCEPT_MAT_CODIFIER_IS_NULL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_CODIFIER_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary cannot contain keys not included in collection parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_MAT_CODIFIER_REFERS_TO_IRRELEVANT_KEY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_CODIFIER_REFERS_TO_IRRELEVANT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix can be converted to the type of its entries only if it is scalar..
        /// </summary>
        internal static string STR_EXCEPT_MAT_CONVERTED_TO_ENTRY_TYPE_MUST_BE_SCALAR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_CONVERTED_TO_ENTRY_TYPE_MUST_BE_SCALAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In division operations, the number of columns of the right operand must match that of the left one..
        /// </summary>
        internal static string STR_EXCEPT_MAT_DIVIDE_COLUMNS_MUST_MATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_DIVIDE_COLUMNS_MUST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In division operations, the right operand cannot be unsquare and rank deficient..
        /// </summary>
        internal static string STR_EXCEPT_MAT_DIVIDE_RANK_DEFICIENT_OPERATION {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_DIVIDE_RANK_DEFICIENT_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In element-wise operations, the dimensions of the right operand must match those of the left one..
        /// </summary>
        internal static string STR_EXCEPT_MAT_ELEMENT_WISE_ALL_DIMS_MUST_MATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_ELEMENT_WISE_ALL_DIMS_MUST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency between dimensions and data..
        /// </summary>
        internal static string STR_EXCEPT_MAT_INCONSISTENCY_DATA_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_INCONSISTENCY_DATA_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In multiplication operations, the number of rows of the right operand must match the number of columns of the left one..
        /// </summary>
        internal static string STR_EXCEPT_MAT_MULTIPLY_INNER_DIMS_MUST_MATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_MULTIPLY_INNER_DIMS_MUST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In subtraction operations, the dimensions of the right operand must match those of the left one..
        /// </summary>
        internal static string STR_EXCEPT_MAT_SUBTRACT_ALL_DIMS_MUST_MATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_SUBTRACT_ALL_DIMS_MUST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative or zero matrix dimensions are not allowed..
        /// </summary>
        internal static string STR_EXCEPT_MAT_UNALLOWED_NON_POSITIVE_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_MAT_UNALLOWED_NON_POSITIVE_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the DataOperation enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_DATA_OPERATION {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_DATA_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the EliteSampleDefinition enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_ELITE_SAMPLE_DEFINITION {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_ELITE_SAMPLE_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the OptimizationGoal enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_OPTIMIZATION_GOAL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_OPTIMIZATION_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the RareEventPerformanceBoundedness enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_RARE_EVENT_PERFORMANCE_BOUNDEDNESS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_RARE_EVENT_PERFORMANCE_BOUNDEDNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the SortDirection enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_SORT_DIRECTION {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_SORT_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a field of the StorageOrder enumeration..
        /// </summary>
        internal static string STR_EXCEPT_NOT_FIELD_OF_STORAGE_ORDER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_NOT_FIELD_OF_STORAGE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not of type {0}..
        /// </summary>
        internal static string STR_EXCEPT_OBJ_HAS_WRONG_TYPE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_OBJ_HAS_WRONG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new basis and the current one must share the same dimension..
        /// </summary>
        internal static string STR_EXCEPT_PAR_BASES_MUST_SHARE_DIMENSION {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_BASES_MUST_SHARE_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter does not represent a valid integer..
        /// </summary>
        internal static string STR_EXCEPT_PAR_CANNOT_PARSE_AS_INT32 {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_CANNOT_PARSE_AS_INT32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must be distinct..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_MUST_BE_DISTINCT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_MUST_BE_DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must be nonnegative..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_MUST_BE_NON_NEGATIVE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_MUST_BE_NON_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must be positive..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must sum up to 1..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_MUST_SUM_TO_1 {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_MUST_SUM_TO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of parameter entries must not differ from an integer more than .001 in absolute value..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_MUST_SUM_TO_INTEGER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_MUST_SUM_TO_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must be in the closed interval [{0}, {1}]..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_NOT_IN_CLOSED_INTERVAL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_NOT_IN_CLOSED_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter entries must be in the open interval ]{0}, {1}[..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ENTRIES_NOT_IN_OPEN_INTERVAL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ENTRIES_NOT_IN_OPEN_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has or contains a value which is not a valid {0} index for parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_INDEX_EXCEEDS_OTHER_PAR_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_INDEX_EXCEEDS_OTHER_PAR_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not a part identifier..
        /// </summary>
        internal static string STR_EXCEPT_PAR_IS_NOT_A_PART_IDENTIFIER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_IS_NOT_A_PART_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s number of columns must agree with the basis dimension..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_BASIS_COMPLIANT_MATRIX {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_BASIS_COMPLIANT_MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s count must agree with the basis dimension..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_BASIS_COMPLIANT_VECTOR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_BASIS_COMPLIANT_VECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a column vector..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_COLUMN_VECTOR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_COLUMN_VECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be greater than parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_GREATER_THAN_OTHER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_GREATER_THAN_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be greater than {0}..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_GREATER_THAN_VALUE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_GREATER_THAN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a Hermitian matrix..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_HERMITIAN {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_HERMITIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than the number of columns in parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER_COLUMNS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than the number of rows in parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER_ROWS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_LESS_THAN_OTHER_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be less than {0}..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_LESS_THAN_VALUE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_LESS_THAN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be non empty..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NON_EMPTY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be non negative..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NON_NEGATIVE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NON_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a non singular matrix..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NON_SINGULAR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NON_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be nonzero..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NONZERO {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NONZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than or equal to parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NOT_GREATER_THAN_OTHER {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NOT_GREATER_THAN_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than or equal to the number of rows in parameter &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NOT_GREATER_THAN_OTHER_ROWS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NOT_GREATER_THAN_OTHER_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be greater than or equal to {0}..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_NOT_LESS_THAN_VALUE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_NOT_LESS_THAN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be positive..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a row vector..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_ROW_VECTOR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_ROW_VECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a square matrix..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_SQUARE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a symmetric matrix..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_BE_SYMMETRIC {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_BE_SYMMETRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter&apos;s count must be equal to that of parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_HAVE_SAME_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_HAVE_SAME_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of columns equal to that of parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_HAVE_SAME_NUM_OF_COLUMNS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_HAVE_SAME_NUM_OF_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of rows equal to that of parameter &apos;{0}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PAR_MUST_HAVE_SAME_NUM_OF_ROWS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_MUST_HAVE_SAME_NUM_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A row or column name cannot match a string reserved for matrix indexing..
        /// </summary>
        internal static string STR_EXCEPT_PAR_NAME_CANNOT_BE_RESERVED_STRING {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_NAME_CANNOT_BE_RESERVED_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements in this instance is greater than the available space from arrayIndex to the end of the destination array..
        /// </summary>
        internal static string STR_EXCEPT_PAR_NOT_ENOUGH_SPACE_IN_ARRAY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_NOT_ENOUGH_SPACE_IN_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be in the closed interval [{0}, {1}]..
        /// </summary>
        internal static string STR_EXCEPT_PAR_NOT_IN_CLOSED_INTERVAL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_NOT_IN_CLOSED_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be in the open interval ]{0}, {1}[..
        /// </summary>
        internal static string STR_EXCEPT_PAR_NOT_IN_OPEN_INTERVAL {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_NOT_IN_OPEN_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must have a number of rows equal to the number of cloud individuals..
        /// </summary>
        internal static string STR_EXCEPT_PAR_ROW_DIM_MUST_MATCH_INDIVIDUALS_COUNT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_ROW_DIM_MUST_MATCH_INDIVIDUALS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter cannot be empty, or consist only of white-space characters..
        /// </summary>
        internal static string STR_EXCEPT_PAR_STRING_IS_EMPTY_OR_WHITESPACE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PAR_STRING_IS_EMPTY_OR_WHITESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invert the cumulative distribution function of this instance..
        /// </summary>
        internal static string STR_EXCEPT_PDF_INVERSE_CDF_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PDF_INVERSE_CDF_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be less than or equal to the difference between the lengths of parameters &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_PDF_SAMPLESIZE_ARRAYLENGTH_MISMATCH {
            get {
                return ResourceManager.GetString("STR_EXCEPT_PDF_SAMPLESIZE_ARRAYLENGTH_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Csv document declares entry type &apos;{0}&apos; but the serializer expects &apos;{1}&apos;..
        /// </summary>
        internal static string STR_EXCEPT_REP_DESERIALIZE_UNEXPECTED_ENTRY_TYPE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_REP_DESERIALIZE_UNEXPECTED_ENTRY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deserialization. Inspect eventual inner exceptions for additional details..
        /// </summary>
        internal static string STR_EXCEPT_REP_UNABLE_TO_DESERIALIZE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_REP_UNABLE_TO_DESERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during serialization. Inspect eventual inner exceptions for additional details..
        /// </summary>
        internal static string STR_EXCEPT_REP_UNABLE_TO_SERIALIZE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_REP_UNABLE_TO_SERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must represent a valid column index for the matrix whose rows this instance is collecting..
        /// </summary>
        internal static string STR_EXCEPT_ROW_DATA_COLUMN_EXCEEDS_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_ROW_DATA_COLUMN_EXCEEDS_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample kurtosis cannot be adjusted for bias if the sample size is less than 4..
        /// </summary>
        internal static string STR_EXCEPT_STA_KURTOSIS_ADJUST_FOR_BIAS_UNDEFINED {
            get {
                return ResourceManager.GetString("STR_EXCEPT_STA_KURTOSIS_ADJUST_FOR_BIAS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample skewness cannot be adjusted for bias if the sample size is less than 3..
        /// </summary>
        internal static string STR_EXCEPT_STA_SKEWNESS_ADJUST_FOR_BIAS_UNDEFINED {
            get {
                return ResourceManager.GetString("STR_EXCEPT_STA_SKEWNESS_ADJUST_FOR_BIAS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample standard deviations, variances or covariances cannot be adjusted for bias if the sample size is less than 2..
        /// </summary>
        internal static string STR_EXCEPT_STA_VARIANCE_ADJUST_FOR_BIAS_UNDEFINED {
            get {
                return ResourceManager.GetString("STR_EXCEPT_STA_VARIANCE_ADJUST_FOR_BIAS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Singular Value Decomposition required to acquire the principal information cannot be executed or does not converge..
        /// </summary>
        internal static string STR_EXCEPT_SVD_ERRORS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_SVD_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assigned collection and the sub-referenced one have unequal dimensions..
        /// </summary>
        internal static string STR_EXCEPT_TAB_INCONSISTENT_SUBASSIGNMENT {
            get {
                return ResourceManager.GetString("STR_EXCEPT_TAB_INCONSISTENT_SUBASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An index exceeds the dimensions of this instance..
        /// </summary>
        internal static string STR_EXCEPT_TAB_INDEX_EXCEEDS_DIMS {
            get {
                return ResourceManager.GetString("STR_EXCEPT_TAB_INDEX_EXCEEDS_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is of a fixed size..
        /// </summary>
        internal static string STR_EXCEPT_TAB_IS_OF_A_FIXED_SIZE {
            get {
                return ResourceManager.GetString("STR_EXCEPT_TAB_IS_OF_A_FIXED_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string STR_EXCEPT_TAB_IS_READ_ONLY {
            get {
                return ResourceManager.GetString("STR_EXCEPT_TAB_IS_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported sub-reference syntax. The argument is not a string reserved for matrix indexing..
        /// </summary>
        internal static string STR_EXCEPT_TAB_UNSUPPORTED_SUBREF_SYNTAX {
            get {
                return ResourceManager.GetString("STR_EXCEPT_TAB_UNSUPPORTED_SUBREF_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the creation of the random stream..
        /// </summary>
        internal static string STR_EXCEPT_VSL_CANNOT_CREATE_STREAM_DESCRIPTOR {
            get {
                return ResourceManager.GetString("STR_EXCEPT_VSL_CANNOT_CREATE_STREAM_DESCRIPTOR", resourceCulture);
            }
        }
    }
}
